version: "2"
linters:
  enable:
    - durationcheck
    - forcetypeassert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forcetypeassert
        path: _test\.go
issues:
  max-same-issues: 0
formatters:
  settings:
    gofumpt:
      module-path: github.com/daioh/flip7_strategy
      extra-rules: true